verbs = [
    "throw",
    "spring",
    "underline",
    "wake up early by 6am",
    "project",
    "reckon",
    "belong",
    "part",
    "reinforce",
    "repair the car clutch",
    "introduce",
    "maintain the tools",
    "lend",
    "ease",
    "enclose",
    "save",
    "follow",
    "label the products",
    "receive",
    "change",
    "listen to music",
    "prove",
    "purchase a new mouse",
    "put",
    "instruct my workers",
    "trace",
    "surprise",
    "undergo",
    "suggest",
    "glance",
    "explode",
    "attract",
    "hurt",
    "beg",
    "buy",
    "halt",
    "criticize",
    "award my self",
    "suspend",
    "mind",
    "upset",
    "oppose",
    "conclude",
    "couple",
    "grasp",
    "improve my self",
    "dissolve",
    "ask questions",
    "stimulate my mind",
    "go to the gym",
    "buy groceries",
    "learn flask",
    "play soccer at the field",
    "jog at least 4 miles",
    "drink water",
]
